### ISSUE TITLE
"Could not load webviz_core_components/notistack.esm.js.map" errors when accessing landing page of webviz apps

### ISSUE THREAD

**Issue by mhwaage** [equinor/webviz-core-components#185]
When first accessing a webviz app, relevant js source files are loaded in. One attempted load is of notistack.esm.js.map, which is dragged in via the plugins. However, notistack.esm.js.map is not present. This causes an error trace in the server logs:
```
Traceback (most recent call last):
  File "/home/mhwa/.cache/pypoetry/virtualenvs/caramba-webviz-iPYFB_Rq-py3.8/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mhwa/.cache/pypoetry/virtualenvs/caramba-webviz-iPYFB_Rq-py3.8/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mhwa/.cache/pypoetry/virtualenvs/caramba-webviz-iPYFB_Rq-py3.8/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mhwa/.cache/pypoetry/virtualenvs/caramba-webviz-iPYFB_Rq-py3.8/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mhwa/.cache/pypoetry/virtualenvs/caramba-webviz-iPYFB_Rq-py3.8/lib/python3.8/site-packages/dash/dash.py", line 778, in serve_component_suites
    _validate.validate_js_path(self.registered_paths, package_name, path_in_pkg)
  File "/home/mhwa/.cache/pypoetry/virtualenvs/caramba-webviz-iPYFB_Rq-py3.8/lib/python3.8/site-packages/dash/_validate.py", line 343, in validate_js_path
    raise exceptions.DependencyException(
dash.exceptions.DependencyException: "webviz_core_components" is registered but the path requested is not valid.
The path requested: "notistack.esm.js.map"
List of registered paths: defaultdict(<class 'set'>, {'dash': {'dcc/dash_core_components.js.map', 'html/dash_html_components.min.js', 'dcc/async-highlight.js', 'dcc/async-upload.js', 'dcc/async-graph.js', 'dcc/async-highlight.js.map', 'dash_table/async-export.js', 'dcc/async-plotlyjs.js', 'dash_table/async-export.js.map', 'dash_table/async-highlight.js', 'dash_table/async-table.js', 'dcc/async-dropdown.js.map', 'deps/prop-types@15.7.2.min.js', 'dcc/async-plotlyjs.js.map', 'deps/polyfill@7.12.1.min.js', 'dcc/dash_core_components-shared.js.map', 'deps/react@16.14.0.min.js', 'dcc/async-datepicker.js', 'dcc/async-markdown.js', 'dcc/async-datepicker.js.map', 'dash-renderer/build/dash_renderer.min.js', 'dash_table/bundle.js', 'dcc/async-dropdown.js', 'dcc/dash_core_components-shared.js', 'dash-renderer/build/dash_renderer.min.js.map', 'dcc/async-graph.js.map', 'dash_table/async-table.js.map', 'html/dash_html_components.min.js.map', 'dcc/plotly.min.js', 'deps/react-dom@16.14.0.min.js', 'dcc/dash_core_components.js', 'dcc/async-markdown.js.map', 'dash_table/bundle.js.map', 'dcc/async-slider.js.map', 'dash_table/async-highlight.js.map', 'dcc/async-upload.js.map', 'dcc/async-slider.js'}, 'dash_pivottable': {'dash_pivottable.min.js'}, 'webviz_core_components': {'webviz_core_components.css', 'webviz_core_components.min.js'}})
```
as well as a warning logged on the dev console side:
![image](https://user-images.githubusercontent.com/57612883/139223666-98dbdde9-d872-4112-b88e-441e4cba1265.png)

Presumably, the file should be included in some manifest?

**Comment by anders-kiaer** [comment]
Also seeing this in production today, but for another path:
```
ERROR:dash_app.webviz_app:Exception on /_dash-component-suites/webviz_core_components/popper.js.map [GET]
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/appuser/.local/lib/python3.6/site-packages/dash/dash.py", line 778, in serve_component_suites
    _validate.validate_js_path(self.registered_paths, package_name, path_in_pkg)
  File "/home/appuser/.local/lib/python3.6/site-packages/dash/_validate.py", line 349, in validate_js_path
    package_name, path_in_package_dist, registered_paths
dash.exceptions.DependencyException: "webviz_core_components" is registered but the path requested is not valid.
The path requested: "popper.js.map
```

Similar issue is seen for `webviz-subsurface-components`:
```
ERROR:dash_app.webviz_app:Exception on /_dash-component-suites/webviz_subsurface_components/styles.css.map [GET]
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/appuser/.local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/appuser/.local/lib/python3.6/site-packages/dash/dash.py", line 778, in serve_component_suites
    _validate.validate_js_path(self.registered_paths, package_name, path_in_pkg)
  File "/home/appuser/.local/lib/python3.6/site-packages/dash/_validate.py", line 349, in validate_js_path
    package_name, path_in_package_dist, registered_paths
dash.exceptions.DependencyException: "webviz_subsurface_components" is registered but the path requested is not valid.
The path requested: "styles.css.map"
```

**Comment by anders-kiaer** [comment]
Might be a similar case as seen in https://github.com/plotly/dash-daq/issues/83.

**Comment by anders-kiaer** [comment]
Something similar also seen by Daniel (Equinor) with this traceback:
```
    raise exceptions.DependencyException(
dash.exceptions.DependencyException: "webviz_core_components" is registered but the path requested is not valid.
The path requested: "popper.js.map"
List of registered paths: defaultdict(<class 'set'>, {'dash': {'dash_table/async-table.js.map', 'dcc/async-plotlyjs.js.map', 'dash_table/async-export.js', 'dcc/async-datepicker.js.map', 'dcc/plotly.min.js', 'dcc/async-dropdown.js', 'dash_table/async-table.js', 'dcc/dash_core_components.js.map', 'deps/polyfill@7.12.1.min.js', 'dash_table/async-highlight.js.map', 'dcc/async-highlight.js.map', 'dash_table/bundle.js.map', 'deps/prop-types@15.8.1.min.js', 'dcc/async-markdown.js', 'dcc/async-slider.js', 'dcc/async-graph.js', 'dash-renderer/build/dash_renderer.min.js', 'deps/react@16.14.0.min.js', 'dcc/async-slider.js.map', 'dcc/async-mathjax.js.map', 'dash_table/async-export.js.map', 'dcc/async-mathjax.js', 'dcc/async-upload.js', 'dash_table/bundle.js', 'dcc/async-upload.js.map', 'dcc/dash_core_components.js', 'dcc/async-plotlyjs.js', 'dcc/async-dropdown.js.map', 'dcc/async-markdown.js.map', 'dcc/async-highlight.js', 'deps/react-dom@16.14.0.min.js', 'html/dash_html_components.min.js', 'dcc/dash_core_components-shared.js.map', 'html/dash_html_components.min.js.map', 'dash-renderer/build/dash_renderer.min.js.map', 'dash_table/async-highlight.js', 'dcc/dash_core_components-shared.js', 'dcc/async-datepicker.js', 'dcc/async-graph.js.map'}, 'webviz_core_components': {'webviz_core_components.css', 'webviz_core_components.min.js'}, 'webviz_subsurface_components': {'webviz_subsurface_components.min.js', 'webviz_subsurface_components.css'}})
```
